// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJiysK4tklhivXeHTV48bmp8srRWntIR8',
    appId: '1:557700744202:web:d5b43833fc1c30e6584bf3',
    messagingSenderId: '557700744202',
    projectId: 'grocery-app-2ec11',
    authDomain: 'grocery-app-2ec11.firebaseapp.com',
    storageBucket: 'grocery-app-2ec11.appspot.com',
    measurementId: 'G-LLNFS501GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm7yhMYsz4FWen5oHAe9nAIOBb0m8Al7o',
    appId: '1:557700744202:android:ce4dab657d6f034a584bf3',
    messagingSenderId: '557700744202',
    projectId: 'grocery-app-2ec11',
    storageBucket: 'grocery-app-2ec11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtxfWQzwD_7Y4kHsrid2pcdneFeZgNHtA',
    appId: '1:557700744202:ios:30fae3ffc94c58e6584bf3',
    messagingSenderId: '557700744202',
    projectId: 'grocery-app-2ec11',
    storageBucket: 'grocery-app-2ec11.appspot.com',
    androidClientId: '557700744202-ik5pgjknvvrcr58r9vgrpch7vr7koao8.apps.googleusercontent.com',
    iosClientId: '557700744202-2bh2dmhgqqgpu7jaf53i3up53bkdpj7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtxfWQzwD_7Y4kHsrid2pcdneFeZgNHtA',
    appId: '1:557700744202:ios:30fae3ffc94c58e6584bf3',
    messagingSenderId: '557700744202',
    projectId: 'grocery-app-2ec11',
    storageBucket: 'grocery-app-2ec11.appspot.com',
    androidClientId: '557700744202-ik5pgjknvvrcr58r9vgrpch7vr7koao8.apps.googleusercontent.com',
    iosClientId: '557700744202-2bh2dmhgqqgpu7jaf53i3up53bkdpj7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryAdmin',
  );
}
